# Generated by Django 2.2 on 2019-08-05 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='credit_Card_Number',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='credit_Card_Type',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='expiration_Date',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='student_ID',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_Card_Type', models.CharField(blank=True, choices=[('M', 'MasterCard'), ('V', 'Visa'), ('A', 'American Express'), ('D', 'Discover')], max_length=1)),
                ('credit_Card_Number', models.CharField(blank=True, max_length=20)),
                ('expiration_Date', models.DateField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
