# Generated by Django 2.2 on 2019-08-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20190805_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='credit_Card_Type',
            field=models.CharField(blank=True, choices=[('V', 'Visa'), ('D', 'Discover'), ('A', 'American Express'), ('M', 'MasterCard')], max_length=1),
        ),
    ]
